# Generated by Django 4.1 on 2022-08-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Position_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_source', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(max_length=10)),
                ('callsign', models.CharField(max_length=10)),
                ('origin_country', models.CharField(max_length=30)),
                ('time_position', models.IntegerField(default=0)),
                ('last_contact', models.IntegerField(default=0)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('geo_altitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('on_ground', models.CharField(max_length=5)),
                ('velocity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('true_track', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vertical_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sensors', models.CharField(max_length=15)),
                ('baro_altitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('squawk', models.IntegerField(default=0)),
                ('spi', models.CharField(max_length=5)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('position_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position_source')),
            ],
        ),
    ]
