# Generated by Django 4.1 on 2022-08-25 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_category_id_state_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AlterField(
            model_name='state',
            name='position_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.position_source'),
        ),
    ]
