# Generated by Django 4.1 on 2022-08-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_state_category_alter_state_position_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='state',
            name='position_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position_source'),
        ),
    ]
